plugins {
    id 'com.android.application' version '8.3.0' apply false
    id 'com.android.library' version '8.3.0' apply false
}

ext {
    minSdk = 24
    targetSdk = 35
    compileSdk = 35
}

subprojects {
    plugins.withId("com.android.application") {
        android {
            compileSdk rootProject.ext.compileSdk
            defaultConfig {
                minSdk rootProject.ext.minSdk
                targetSdk rootProject.ext.targetSdk
                versionCode 1
                versionName "1.0"
            }
            compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
            buildTypes {
                release {
                    minifyEnabled false
                    debuggable false
                }
                debug {
                    minifyEnabled false
                    debuggable true
                }
            }
        }
    }
}


dependencies {
    implementation "androidx.activity:activity:1.9.2"
    implementation "androidx.appcompat:appcompat:1.7.0"

}
