plugins {
    id 'com.android.application'
}

android {
    namespace 'com.github.ekodomo3.imgbb'
    compileSdk 34

    defaultConfig {
        applicationId 'com.github.ekodomo3.imgbb'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'
    implementation "androidx.activity:activity:1.9.2"
    implementation "androidx.appcompat:appcompat:1.7.0"
    
    implementation project(':basemodule')
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.11.0'
}
