name: Build and Release APK

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Generate Release Keystore
        run: keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-alias -storepass password123 -keypass password123 -dname "CN=ImgBB, OU=Plugin, O=Zettel, L=Mysuru, S=KA, C=IN"

      - name: Build Release APK
        run: ./gradlew :plugin-btn-imgbb:assembleRelease -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/my-release-key.jks -Pandroid.injected.signing.store.password=password123 -Pandroid.injected.signing.key.alias=my-alias -Pandroid.injected.signing.key.password=password123 --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: imgbb-plugin-release
          path: plugin-btn-imgbb/build/outputs/apk/release/*.apk
          if-no-files-found: error
